// Fixture de la fase de grupos y fases eliminatorias del Mundial 2026 (104 partidos).
// Autogenerado a partir de la lista oficial provista por el usuario con goles e índices de bracket incorporados.

export interface FixturePartido {
  homeTeam: string
  awayTeam: string
  group: string | null
  stadium: string
  city: string
  kickoff: string
  stage: 'Fase de grupos' | 'Dieciseisavos' | 'Octavos' | 'Cuartos' | 'Semifinal' | 'Tercer lugar' | 'Final'
  status?: string
  homeScore?: number | null
  awayScore?: number | null
  bracketPosition?: number | null
}

export const FIXTURE_FASE_GRUPOS: FixturePartido[] = [
  {
    homeTeam: "México",
    awayTeam: "Sudáfrica",
    group: "A",
    stadium: "Estadio Azteca",
    city: "Ciudad de México",
    kickoff: "2026-06-11T13:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "Corea del Sur",
    awayTeam: "República Checa",
    group: "A",
    stadium: "Estadio Akron",
    city: "Guadalajara",
    kickoff: "2026-06-11T16:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Canadá",
    awayTeam: "Bosnia y Herzegovina",
    group: "B",
    stadium: "BMO Field",
    city: "Toronto",
    kickoff: "2026-06-12T13:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Estados Unidos",
    awayTeam: "Paraguay",
    group: "D",
    stadium: "SoFi Stadium",
    city: "Los Ángeles",
    kickoff: "2026-06-12T16:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 4,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Catar",
    awayTeam: "Suiza",
    group: "B",
    stadium: "Levi's Stadium",
    city: "San Francisco",
    kickoff: "2026-06-13T13:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Brasil",
    awayTeam: "Marruecos",
    group: "C",
    stadium: "MetLife Stadium",
    city: "Nueva York / Nueva Jersey",
    kickoff: "2026-06-13T16:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Haití",
    awayTeam: "Escocia",
    group: "C",
    stadium: "Gillette Stadium",
    city: "Boston",
    kickoff: "2026-06-13T19:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Australia",
    awayTeam: "Turquía",
    group: "D",
    stadium: "BC Place",
    city: "Vancouver",
    kickoff: "2026-06-13T21:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "Alemania",
    awayTeam: "Curazao",
    group: "E",
    stadium: "NRG Stadium",
    city: "Houston",
    kickoff: "2026-06-14T13:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 7,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Países Bajos",
    awayTeam: "Japón",
    group: "F",
    stadium: "AT&T Stadium",
    city: "Dallas",
    kickoff: "2026-06-14T16:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 2,
    bracketPosition: null
  },
  {
    homeTeam: "Costa de Marfil",
    awayTeam: "Ecuador",
    group: "E",
    stadium: "Lincoln Financial Field",
    city: "Filadelfia",
    kickoff: "2026-06-14T19:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "Ganador Playoff UEFA B",
    awayTeam: "Túnez",
    group: "F",
    stadium: "Estadio BBVA",
    city: "Monterrey",
    kickoff: "2026-06-14T21:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 5,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "España",
    awayTeam: "Cabo Verde",
    group: "H",
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    kickoff: "2026-06-15T13:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "Bélgica",
    awayTeam: "Egipto",
    group: "G",
    stadium: "Lumen Field",
    city: "Seattle",
    kickoff: "2026-06-15T16:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Arabia Saudita",
    awayTeam: "Uruguay",
    group: "H",
    stadium: "Hard Rock Stadium",
    city: "Miami",
    kickoff: "2026-06-15T19:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Irán",
    awayTeam: "Nueva Zelanda",
    group: "G",
    stadium: "SoFi Stadium",
    city: "Los Ángeles",
    kickoff: "2026-06-15T21:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 2,
    bracketPosition: null
  },
  {
    homeTeam: "Francia",
    awayTeam: "Senegal",
    group: "I",
    stadium: "MetLife Stadium",
    city: "Nueva York / Nueva Jersey",
    kickoff: "2026-06-16T13:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 3,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Ganador Playoff Intercontinental 2",
    awayTeam: "Noruega",
    group: "I",
    stadium: "Gillette Stadium",
    city: "Boston",
    kickoff: "2026-06-16T16:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 4,
    bracketPosition: null
  },
  {
    homeTeam: "Argentina",
    awayTeam: "Argelia",
    group: "J",
    stadium: "Arrowhead Stadium",
    city: "Kansas City",
    kickoff: "2026-06-16T19:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 3,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "Austria",
    awayTeam: "Jordania",
    group: "J",
    stadium: "Levi's Stadium",
    city: "San Francisco",
    kickoff: "2026-06-16T21:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 3,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Portugal",
    awayTeam: "Ganador Playoff Intercontinental 1",
    group: "K",
    stadium: "NRG Stadium",
    city: "Houston",
    kickoff: "2026-06-17T13:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Inglaterra",
    awayTeam: "Croacia",
    group: "L",
    stadium: "AT&T Stadium",
    city: "Dallas",
    kickoff: "2026-06-17T16:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 4,
    awayScore: 2,
    bracketPosition: null
  },
  {
    homeTeam: "Ghana",
    awayTeam: "Panamá",
    group: "L",
    stadium: "BMO Field",
    city: "Toronto",
    kickoff: "2026-06-17T19:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "Uzbekistán",
    awayTeam: "Colombia",
    group: "K",
    stadium: "Estadio Azteca",
    city: "Ciudad de México",
    kickoff: "2026-06-17T21:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 3,
    bracketPosition: null
  },
  {
    homeTeam: "Suiza",
    awayTeam: "Canadá",
    group: "B",
    stadium: "BC Place",
    city: "Vancouver",
    kickoff: "2026-06-24T13:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Bosnia y Herzegovina",
    awayTeam: "Catar",
    group: "B",
    stadium: "Lumen Field",
    city: "Seattle",
    kickoff: "2026-06-24T16:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 4,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Escocia",
    awayTeam: "Brasil",
    group: "C",
    stadium: "Hard Rock Stadium",
    city: "Miami",
    kickoff: "2026-06-24T19:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 6,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "Marruecos",
    awayTeam: "Haití",
    group: "C",
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    kickoff: "2026-06-24T21:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "República Checa",
    awayTeam: "México",
    group: "A",
    stadium: "Estadio Azteca",
    city: "Ciudad de México",
    kickoff: "2026-06-24T22:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "Sudáfrica",
    awayTeam: "Corea del Sur",
    group: "A",
    stadium: "Estadio BBVA",
    city: "Monterrey",
    kickoff: "2026-06-24T22:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Curazao",
    awayTeam: "Costa de Marfil",
    group: "E",
    stadium: "Lincoln Financial Field",
    city: "Filadelfia",
    kickoff: "2026-06-25T13:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 3,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "Ecuador",
    awayTeam: "Alemania",
    group: "E",
    stadium: "MetLife Stadium",
    city: "Nueva York / Nueva Jersey",
    kickoff: "2026-06-25T16:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Japón",
    awayTeam: "Suecia",
    group: "F",
    stadium: "AT&T Stadium",
    city: "Dallas",
    kickoff: "2026-06-25T19:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 5,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Túnez",
    awayTeam: "Países Bajos",
    group: "F",
    stadium: "Arrowhead Stadium",
    city: "Kansas City",
    kickoff: "2026-06-25T21:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Turquía",
    awayTeam: "Estados Unidos",
    group: "D",
    stadium: "SoFi Stadium",
    city: "Los Ángeles",
    kickoff: "2026-06-25T22:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "Paraguay",
    awayTeam: "Australia",
    group: "D",
    stadium: "Levi's Stadium",
    city: "San Francisco",
    kickoff: "2026-06-25T22:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 4,
    bracketPosition: null
  },
  {
    homeTeam: "Noruega",
    awayTeam: "Francia",
    group: "I",
    stadium: "Gillette Stadium",
    city: "Boston",
    kickoff: "2026-06-26T13:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 4,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "Senegal",
    awayTeam: "Irak",
    group: "I",
    stadium: "BMO Field",
    city: "Toronto",
    kickoff: "2026-06-26T16:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "Cabo Verde",
    awayTeam: "Arabia Saudita",
    group: "H",
    stadium: "NRG Stadium",
    city: "Houston",
    kickoff: "2026-06-26T19:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 2,
    bracketPosition: null
  },
  {
    homeTeam: "Uruguay",
    awayTeam: "España",
    group: "H",
    stadium: "Estadio Akron",
    city: "Guadalajara",
    kickoff: "2026-06-26T21:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 3,
    bracketPosition: null
  },
  {
    homeTeam: "Egipto",
    awayTeam: "Irán",
    group: "G",
    stadium: "Lumen Field",
    city: "Seattle",
    kickoff: "2026-06-26T22:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "Nueva Zelanda",
    awayTeam: "Bélgica",
    group: "G",
    stadium: "BC Place",
    city: "Vancouver",
    kickoff: "2026-06-26T22:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 3,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "Panamá",
    awayTeam: "Inglaterra",
    group: "L",
    stadium: "MetLife Stadium",
    city: "Nueva York / Nueva Jersey",
    kickoff: "2026-06-27T13:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 3,
    awayScore: 2,
    bracketPosition: null
  },
  {
    homeTeam: "Croacia",
    awayTeam: "Ghana",
    group: "L",
    stadium: "Lincoln Financial Field",
    city: "Filadelfia",
    kickoff: "2026-06-27T16:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 2,
    bracketPosition: null
  },
  {
    homeTeam: "Colombia",
    awayTeam: "Portugal",
    group: "K",
    stadium: "Hard Rock Stadium",
    city: "Miami",
    kickoff: "2026-06-27T19:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 5,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "RD del Congo",
    awayTeam: "Uzbekistán",
    group: "K",
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    kickoff: "2026-06-27T21:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "Argelia",
    awayTeam: "Austria",
    group: "J",
    stadium: "Arrowhead Stadium",
    city: "Kansas City",
    kickoff: "2026-06-27T22:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Jordania",
    awayTeam: "Argentina",
    group: "J",
    stadium: "AT&T Stadium",
    city: "Dallas",
    kickoff: "2026-06-27T22:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "México",
    awayTeam: "Corea del Sur",
    group: "A",
    stadium: "Estadio Akron",
    city: "Guadalajara",
    kickoff: "2026-06-19T13:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "República Checa",
    awayTeam: "Sudáfrica",
    group: "A",
    stadium: "Estadio BBVA",
    city: "Monterrey",
    kickoff: "2026-06-24T22:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 3,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Canadá",
    awayTeam: "Catar",
    group: "B",
    stadium: "BC Place",
    city: "Vancouver",
    kickoff: "2026-06-19T16:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 3,
    bracketPosition: null
  },
  {
    homeTeam: "Suiza",
    awayTeam: "Bosnia y Herzegovina",
    group: "B",
    stadium: "SoFi Stadium",
    city: "Los Ángeles",
    kickoff: "2026-06-19T19:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 4,
    awayScore: 2,
    bracketPosition: null
  },
  {
    homeTeam: "Brasil",
    awayTeam: "Haití",
    group: "C",
    stadium: "Lincoln Financial Field",
    city: "Filadelfia",
    kickoff: "2026-06-19T21:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 3,
    bracketPosition: null
  },
  {
    homeTeam: "Escocia",
    awayTeam: "Marruecos",
    group: "C",
    stadium: "Gillette Stadium",
    city: "Boston",
    kickoff: "2026-06-19T22:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "Estados Unidos",
    awayTeam: "Australia",
    group: "D",
    stadium: "Estadio Seattle",
    city: "Seattle",
    kickoff: "2026-06-19T22:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 2,
    bracketPosition: null
  },
  {
    homeTeam: "Turquía",
    awayTeam: "Paraguay",
    group: "D",
    stadium: "Levi's Stadium",
    city: "San Francisco",
    kickoff: "2026-06-19T22:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Alemania",
    awayTeam: "Costa de Marfil",
    group: "E",
    stadium: "Estadio Toronto",
    city: "Toronto",
    kickoff: "2026-06-20T13:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Ecuador",
    awayTeam: "Curazao",
    group: "E",
    stadium: "Arrowhead Stadium",
    city: "Kansas City",
    kickoff: "2026-06-20T16:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 3,
    bracketPosition: null
  },
  {
    homeTeam: "Países Bajos",
    awayTeam: "Suecia",
    group: "F",
    stadium: "NRG Stadium",
    city: "Houston",
    kickoff: "2026-06-20T19:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 3,
    awayScore: 2,
    bracketPosition: null
  },
  {
    homeTeam: "Túnez",
    awayTeam: "Japón",
    group: "F",
    stadium: "Estadio BBVA",
    city: "Monterrey",
    kickoff: "2026-06-20T21:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "Bélgica",
    awayTeam: "Irán",
    group: "G",
    stadium: "SoFi Stadium",
    city: "Los Ángeles",
    kickoff: "2026-06-21T13:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 4,
    bracketPosition: null
  },
  {
    homeTeam: "Nueva Zelanda",
    awayTeam: "Egipto",
    group: "G",
    stadium: "BC Place",
    city: "Vancouver",
    kickoff: "2026-06-21T16:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 5,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "España",
    awayTeam: "Arabia Saudita",
    group: "H",
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    kickoff: "2026-06-21T19:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "Uruguay",
    awayTeam: "Cabo Verde",
    group: "H",
    stadium: "Hard Rock Stadium",
    city: "Miami",
    kickoff: "2026-06-21T21:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Francia",
    awayTeam: "Irak",
    group: "I",
    stadium: "Lincoln Financial Field",
    city: "Filadelfia",
    kickoff: "2026-06-22T13:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Noruega",
    awayTeam: "Senegal",
    group: "I",
    stadium: "MetLife Stadium",
    city: "Nueva York / Nueva Jersey",
    kickoff: "2026-06-22T16:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 5,
    bracketPosition: null
  },
  {
    homeTeam: "Argentina",
    awayTeam: "Austria",
    group: "J",
    stadium: "AT&T Stadium",
    city: "Dallas",
    kickoff: "2026-06-22T19:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 2,
    bracketPosition: null
  },
  {
    homeTeam: "Jordania",
    awayTeam: "Argelia",
    group: "J",
    stadium: "Levi's Stadium",
    city: "San Francisco",
    kickoff: "2026-06-22T21:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Portugal",
    awayTeam: "Uzbekistán",
    group: "K",
    stadium: "NRG Stadium",
    city: "Houston",
    kickoff: "2026-06-23T13:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 0,
    bracketPosition: null
  },
  {
    homeTeam: "Colombia",
    awayTeam: "RD del Congo",
    group: "K",
    stadium: "Estadio Akron",
    city: "Guadalajara",
    kickoff: "2026-06-23T16:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 3,
    awayScore: 1,
    bracketPosition: null
  },
  {
    homeTeam: "Inglaterra",
    awayTeam: "Ghana",
    group: "L",
    stadium: "Gillette Stadium",
    city: "Boston",
    kickoff: "2026-06-23T19:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 3,
    awayScore: 3,
    bracketPosition: null
  },
  {
    homeTeam: "Panamá",
    awayTeam: "Croacia",
    group: "L",
    stadium: "Estadio Toronto",
    city: "Toronto",
    kickoff: "2026-06-23T21:00:00",
    stage: "Fase de grupos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 3,
    bracketPosition: null
  },
  {
    homeTeam: "Sudáfrica",
    awayTeam: "Canadá",
    group: null,
    stadium: "SoFi Stadium",
    city: "Los Ángeles",
    kickoff: "2026-06-28T13:00:00",
    stage: "Dieciseisavos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 1,
    bracketPosition: 0
  },
  {
    homeTeam: "Brasil",
    awayTeam: "Japón",
    group: null,
    stadium: "NRG Stadium",
    city: "Houston",
    kickoff: "2026-06-29T13:00:00",
    stage: "Dieciseisavos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 1,
    bracketPosition: 1
  },
  {
    homeTeam: "Alemania",
    awayTeam: "Paraguay",
    group: null,
    stadium: "Gillette Stadium",
    city: "Boston",
    kickoff: "2026-06-29T16:00:00",
    stage: "Dieciseisavos",
    status: "Finalizado",
    homeScore: 3,
    awayScore: 4,
    bracketPosition: 2
  },
  {
    homeTeam: "Países Bajos",
    awayTeam: "Marruecos",
    group: null,
    stadium: "Estadio BBVA",
    city: "Monterrey",
    kickoff: "2026-06-29T19:00:00",
    stage: "Dieciseisavos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 3,
    bracketPosition: 3
  },
  {
    homeTeam: "Costa de Marfil",
    awayTeam: "Noruega",
    group: null,
    stadium: "AT&T Stadium",
    city: "Dallas",
    kickoff: "2026-06-30T13:00:00",
    stage: "Dieciseisavos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 2,
    bracketPosition: 4
  },
  {
    homeTeam: "Francia",
    awayTeam: "Suecia",
    group: null,
    stadium: "MetLife Stadium",
    city: "Nueva York / Nueva Jersey",
    kickoff: "2026-06-30T16:00:00",
    stage: "Dieciseisavos",
    status: "Finalizado",
    homeScore: 3,
    awayScore: 0,
    bracketPosition: 5
  },
  {
    homeTeam: "México",
    awayTeam: "Ecuador",
    group: null,
    stadium: "Estadio Azteca",
    city: "Ciudad de México",
    kickoff: "2026-06-30T19:00:00",
    stage: "Dieciseisavos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 0,
    bracketPosition: 6
  },
  {
    homeTeam: "Inglaterra",
    awayTeam: "RD del Congo",
    group: null,
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    kickoff: "2026-07-01T13:00:00",
    stage: "Dieciseisavos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 1,
    bracketPosition: 7
  },
  {
    homeTeam: "Bélgica",
    awayTeam: "Senegal",
    group: null,
    stadium: "Lumen Field",
    city: "Seattle",
    kickoff: "2026-07-01T16:00:00",
    stage: "Dieciseisavos",
    status: "Finalizado",
    homeScore: 3,
    awayScore: 2,
    bracketPosition: 8
  },
  {
    homeTeam: "Estados Unidos",
    awayTeam: "Bosnia y Herzegovina",
    group: null,
    stadium: "Levi's Stadium",
    city: "San Francisco",
    kickoff: "2026-07-01T19:00:00",
    stage: "Dieciseisavos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 0,
    bracketPosition: 9
  },
  {
    homeTeam: "España",
    awayTeam: "Austria",
    group: null,
    stadium: "SoFi Stadium",
    city: "Los Ángeles",
    kickoff: "2026-07-02T13:00:00",
    stage: "Dieciseisavos",
    status: "Finalizado",
    homeScore: 3,
    awayScore: 0,
    bracketPosition: 10
  },
  {
    homeTeam: "Portugal",
    awayTeam: "Croacia",
    group: null,
    stadium: "BMO Field",
    city: "Toronto",
    kickoff: "2026-07-02T16:00:00",
    stage: "Dieciseisavos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 1,
    bracketPosition: 11
  },
  {
    homeTeam: "Suiza",
    awayTeam: "Argelia",
    group: null,
    stadium: "BC Place",
    city: "Vancouver",
    kickoff: "2026-07-02T19:00:00",
    stage: "Dieciseisavos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 0,
    bracketPosition: 12
  },
  {
    homeTeam: "Australia",
    awayTeam: "Egipto",
    group: null,
    stadium: "AT&T Stadium",
    city: "Dallas",
    kickoff: "2026-07-03T13:00:00",
    stage: "Dieciseisavos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 4,
    bracketPosition: 13
  },
  {
    homeTeam: "Argentina",
    awayTeam: "Cabo Verde",
    group: null,
    stadium: "Hard Rock Stadium",
    city: "Miami",
    kickoff: "2026-07-03T16:00:00",
    stage: "Dieciseisavos",
    status: "Finalizado",
    homeScore: 3,
    awayScore: 2,
    bracketPosition: 14
  },
  {
    homeTeam: "Colombia",
    awayTeam: "Ghana",
    group: null,
    stadium: "Arrowhead Stadium",
    city: "Kansas City",
    kickoff: "2026-07-03T19:00:00",
    stage: "Dieciseisavos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 0,
    bracketPosition: 15
  },
  {
    homeTeam: "Canadá",
    awayTeam: "Marruecos",
    group: null,
    stadium: "NRG Stadium",
    city: "Houston",
    kickoff: "2026-07-04T13:00:00",
    stage: "Octavos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 3,
    bracketPosition: 0
  },
  {
    homeTeam: "Paraguay",
    awayTeam: "Francia",
    group: null,
    stadium: "Lincoln Financial Field",
    city: "Filadelfia",
    kickoff: "2026-07-04T16:00:00",
    stage: "Octavos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 1,
    bracketPosition: 1
  },
  {
    homeTeam: "Brasil",
    awayTeam: "Noruega",
    group: null,
    stadium: "MetLife Stadium",
    city: "Nueva York / Nueva Jersey",
    kickoff: "2026-07-05T13:00:00",
    stage: "Octavos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 2,
    bracketPosition: 2
  },
  {
    homeTeam: "México",
    awayTeam: "Inglaterra",
    group: null,
    stadium: "Estadio Azteca",
    city: "Ciudad de México",
    kickoff: "2026-07-05T16:00:00",
    stage: "Octavos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 3,
    bracketPosition: 3
  },
  {
    homeTeam: "Portugal",
    awayTeam: "España",
    group: null,
    stadium: "AT&T Stadium",
    city: "Dallas",
    kickoff: "2026-07-06T13:00:00",
    stage: "Octavos",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 1,
    bracketPosition: 4
  },
  {
    homeTeam: "Estados Unidos",
    awayTeam: "Bélgica",
    group: null,
    stadium: "Lumen Field",
    city: "Seattle",
    kickoff: "2026-07-06T16:00:00",
    stage: "Octavos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 4,
    bracketPosition: 5
  },
  {
    homeTeam: "Argentina",
    awayTeam: "Egipto",
    group: null,
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    kickoff: "2026-07-07T13:00:00",
    stage: "Octavos",
    status: "Finalizado",
    homeScore: 3,
    awayScore: 2,
    bracketPosition: 6
  },
  {
    homeTeam: "Suiza",
    awayTeam: "Colombia",
    group: null,
    stadium: "BC Place",
    city: "Vancouver",
    kickoff: "2026-07-07T16:00:00",
    stage: "Octavos",
    status: "Finalizado",
    homeScore: 4,
    awayScore: 3,
    bracketPosition: 7
  },
  {
    homeTeam: "Francia",
    awayTeam: "Marruecos",
    group: null,
    stadium: "Gillette Stadium",
    city: "Boston",
    kickoff: "2026-07-09T13:00:00",
    stage: "Cuartos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 0,
    bracketPosition: 0
  },
  {
    homeTeam: "España",
    awayTeam: "Bélgica",
    group: null,
    stadium: "SoFi Stadium",
    city: "Los Ángeles",
    kickoff: "2026-07-10T13:00:00",
    stage: "Cuartos",
    status: "Finalizado",
    homeScore: 2,
    awayScore: 1,
    bracketPosition: 1
  },
  {
    homeTeam: "Noruega",
    awayTeam: "Inglaterra",
    group: null,
    stadium: "Hard Rock Stadium",
    city: "Miami",
    kickoff: "2026-07-11T13:00:00",
    stage: "Cuartos",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 2,
    bracketPosition: 2
  },
  {
    homeTeam: "Argentina",
    awayTeam: "Suiza",
    group: null,
    stadium: "Arrowhead Stadium",
    city: "Kansas City",
    kickoff: "2026-07-11T16:00:00",
    stage: "Cuartos",
    status: "Finalizado",
    homeScore: 3,
    awayScore: 1,
    bracketPosition: 3
  },
  {
    homeTeam: "Francia",
    awayTeam: "España",
    group: null,
    stadium: "AT&T Stadium",
    city: "Dallas",
    kickoff: "2026-07-14T13:00:00",
    stage: "Semifinal",
    status: "Finalizado",
    homeScore: 0,
    awayScore: 2,
    bracketPosition: 0
  },
  {
    homeTeam: "Inglaterra",
    awayTeam: "Argentina",
    group: null,
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    kickoff: "2026-07-15T13:00:00",
    stage: "Semifinal",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 2,
    bracketPosition: 1
  },
  {
    homeTeam: "Francia",
    awayTeam: "Inglaterra",
    group: null,
    stadium: "Hard Rock Stadium",
    city: "Miami",
    kickoff: "2026-07-18T13:00:00",
    stage: "Tercer lugar",
    status: "Finalizado",
    homeScore: 4,
    awayScore: 6,
    bracketPosition: 0
  },
  {
    homeTeam: "España",
    awayTeam: "Argentina",
    group: null,
    stadium: "MetLife Stadium",
    city: "Nueva York / Nueva Jersey",
    kickoff: "2026-07-19T13:00:00",
    stage: "Final",
    status: "Finalizado",
    homeScore: 1,
    awayScore: 0,
    bracketPosition: 0
  },
];
